### ISSUE TITLE
Add this for New Google Places API

### ISSUE THREAD

**Issue by mjbrancato** [chenyuan/SPGooglePlacesAutocomplete#12]
Google Places API now uses an attribute called "place_id" for place reference. Please update SPGooglePlacesAutocompletePlace to the following:

Update to this in interface file:

+ (SPGooglePlacesAutocompletePlace *)placeFromDictionary:(NSDictionary *)placeDictionary apiKey:(NSString *)apiKey
{
    SPGooglePlacesAutocompletePlace *place = [[self alloc] init];
    place.name = placeDictionary[@"description"];
    place.reference = placeDictionary[@"reference"];
    place.identifier = placeDictionary[@"id"];
    place.place_id = placeDictionary[@"place_id"];

    place.type = SPPlaceTypeFromDictionary(placeDictionary);
    place.key = apiKey;
    return place;
}

- (NSString *)description {
    return [NSString stringWithFormat:@"Name: %@, Reference: %@, Identifier: %@, Type: %@, Place ID: %@",
            self.name, self.reference, self.identifier, SPPlaceTypeStringForPlaceType(self.type), self.place_id];
}

- Add this to top of interface: @property (nonatomic, strong) NSString *place_id;
- Add this to header: @property (nonatomic, strong, readonly) NSString *place_id;

**Comment by chenyuan** [comment]
fixed in pull request: https://github.com/chenyuan/SPGooglePlacesAutocomplete/pull/14
