### ISSUE TITLE
Autocomplete using swift language

### ISSUE THREAD

**Issue by Dhanam30** [chenyuan/SPGooglePlacesAutocomplete#15]
Hi 
How to use?Autocomplete using swift language.

**Comment by gali8** [comment]
You must to use a bridge file.
- Create a PROJECTNAME-Bridging-Header.h header file. 
- Write inside #import "SPGooglePlacesAutocomplete.h"
- Compile

That's all! Now you can write Swift code calling Objective-C code like here:

```swift
let _query = SPGooglePlacesAutocompleteQuery(apiKey: GoogleApiKeyWeb)
_query!.location = myLocation
_query!.language = DeviceHelper.getDeviceLanguage()
_query!.types = SPGooglePlacesAutocompletePlaceType.PlaceTypeGeocode

```

**Comment by AnthonyMDev** [comment]
CocoaPods now supports Swift natively. You should be able to use this pod as a swift framework, but for some reason a framework is not being generated for this library.

**Comment by chenyuan** [comment]
please try: https://github.com/chenyuan/SPGooglePlacesAutocomplete
