### ISSUE TITLE
Need SPGooglePlacesPlaceDetailQuery from original project

### ISSUE THREAD

**Issue by frankbaffle** [chenyuan/SPGooglePlacesAutocomplete#16]
The original project contains the class **SPGooglePlacesPlaceDetailQuery**. This query takes the **reference** property of an **SPGooglePlacesAutocompletePlace** object and returns details for that google place. In particular, it provides the lat/long which corresponds exactly to the **SPGooglePlacesAutocompletePlace** object.

Please see here:
https://github.com/spoletto/SPGooglePlacesAutocomplete/blob/master/SPGooglePlacesAutocomplete/SPGooglePlacesPlaceDetailQuery.m

Would it make sense to include this class in this fork?

**Comment by chenyuan** [comment]
@frankbaffle it's kind of late, but are you happy to send pull request to correct this?

**Comment by chenyuan** [comment]
@frankbaffle please start using https://github.com/chenyuan/SPGooglePlacesAutocomplete
