### ISSUE TITLE
Geocoding Google Places API establishment formatted address is incorrect

### ISSUE THREAD

**Issue by Fortisque** [chenyuan/SPGooglePlacesAutocomplete#21]
https://github.com/chenyuan/SPGooglePlacesAutocomplete/blob/master/SPGooglePlacesAutocomplete/SPGooglePlacesAutocompletePlace.m#L52 - This line of code simply geocodes what the google maps api returns as "formatted_address". However this can sometimes be problematic.

I was using the API to call Berkeley places and as an example "Cory Hall: Hearst Avenue @ LeRoy Avenue" returns "United States" as it's formatted_address. However the Google Places API directly returns the correct lat/lng information and other necessary information to create a CLPlacemark, whereas geocoding on "United States" will be inaccurate.

Additionally searching for "Soda Hall, Berkeley, CA, United States" returns "Berkeley, CA 94704, United States" as the formatted address. Soda Hall is to the north of the UC Berkeley campus at Leroy and Hearst, however geocoding "Berkeley, CA 94704, United States" is to the south of the Berkeley Campus.

I made a workaround by directly calling the SPGooglePlacesPlaceDetailQuery myself. Copying the code up until this point https://github.com/chenyuan/SPGooglePlacesAutocomplete/blob/master/SPGooglePlacesAutocomplete/SPGooglePlacesAutocompletePlace.m#L47 and then directly using the placeDictionary [placeDictionary[@"geometry"][@"location"][@"lat"] doubleValue] + @"lng" to construct a CLLocation which I can use in my app rather than letting the @"formatted_adddress" get geocoded.

This behavior is reproducible on the demo. It appears to work fine in the demo though if the function  -resolveGecodePlaceToPlacemark is used instead of -resolveEstablishmentPlaceToPlacemark

Searching for Cory Hall
![screenshot 2015-03-10 09 40 11](https://cloud.githubusercontent.com/assets/3837291/6579956/b32b4448-c70a-11e4-9f25-c22b78bf094e.png)

placeDictionary information - note the 3rd json value "formatted_address" is "United States"
![screenshot 2015-03-10 09 40 42](https://cloud.githubusercontent.com/assets/3837291/6583075/fd175aa6-c71e-11e4-92c0-a146e495fff8.png)

Result of geocoding "United States"
![screenshot 2015-03-10 09 16 15](https://cloud.githubusercontent.com/assets/3837291/6579967/c6da7aea-c70a-11e4-9964-a999a9726ae8.png)

**Comment by chenyuan** [comment]
@Fortisque i know it's kind of too late, but are you happy to submit a pull request? since you've spent time on investigating this issue...

**Comment by chenyuan** [comment]
@Fortisque please try https://github.com/chenyuan/SPGooglePlacesAutocomplete which is being actively maintained. thanks
