### ISSUE TITLE
SPGooglePlacesAutocompleteQuery.h:65:23: Unknown type name 'CGFloat'

### ISSUE THREAD

**Issue by red010182** [chenyuan/SPGooglePlacesAutocomplete#23]
I've installed this repo by cocoa pod and added UIKit, Core Graphics, MapKit frameworks in my project. 

But it still shows this error. 

`SPGooglePlacesAutocompleteQuery.h:65:23: Unknown type name 'CGFloat'`

If I modify the `SPGooglePlacesAutocompleteQuery.h` adding one line of code to import necessary library, it shows ` The document SPGooglePlacesAutocompleteQuery.h could not be saved. The file doesn’t exist`, as someone pointed out in stackoverflow here.

http://stackoverflow.com/questions/28444966/xcode-error-with-cocoapod-the-document-could-not-be-saved-the-file-doesn-t-ex

How to fix this?

**Comment by hkellaway** [comment]
+1

**Comment by chenyuan** [comment]
@hkellaway thanks for making https://github.com/chenyuan/SPGooglePlacesAutocomplete, it looks way better

**Comment by hkellaway** [comment]
:+1+ thanks for the mention
