### ISSUE TITLE
Request Denied

### ISSUE THREAD

**Issue by chennuruashok** [chenyuan/SPGooglePlacesAutocomplete#24]
Am generated the new API key by enabling Google places API for iOS and Ios SDK also. while running and searching the places "" Could not fetch Places" "Request Denied" error is displaying, Can anyone help on this
![screen shot 2015-06-20 at 3 04 10 pm](https://cloud.githubusercontent.com/assets/8543618/8266761/a6ca67bc-175d-11e5-9622-b89bfaa11959.png)

**Comment by trostli** [comment]
I believe you need to use the Google places API key for browser not iOS

**Comment by chenyuan** [comment]
@trostli thanks for helping out.
